// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const activateAccount = `-- name: ActivateAccount :exec
UPDATE account
SET status = 'active'
WHERE account_id = $1
`

func (q *Queries) ActivateAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, activateAccount, accountID)
	return err
}

const createAccountWithOAuth = `-- name: CreateAccountWithOAuth :one
INSERT INTO account (email, username, avatar, status, oauth_provider, oauth_provider_id)
VALUES ($1, $2, $3, 'active', $4, $5)
RETURNING account_id, email, username, password, avatar, cover, description, status, oauth_provider, oauth_provider_id, token_version
`

type CreateAccountWithOAuthParams struct {
	Email           string         `json:"email"`
	Username        string         `json:"username"`
	Avatar          string         `json:"avatar"`
	OauthProvider   sql.NullString `json:"oauth_provider"`
	OauthProviderID sql.NullString `json:"oauth_provider_id"`
}

func (q *Queries) CreateAccountWithOAuth(ctx context.Context, arg CreateAccountWithOAuthParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccountWithOAuth,
		arg.Email,
		arg.Username,
		arg.Avatar,
		arg.OauthProvider,
		arg.OauthProviderID,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Avatar,
		&i.Cover,
		&i.Description,
		&i.Status,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.TokenVersion,
	)
	return i, err
}

const createAccountWithPassword = `-- name: CreateAccountWithPassword :one
INSERT INTO account (email, username, password)
VALUES ($1, $2, $3)
RETURNING account_id, email, username, password, avatar, cover, description, status, oauth_provider, oauth_provider_id, token_version
`

type CreateAccountWithPasswordParams struct {
	Email    string         `json:"email"`
	Username string         `json:"username"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) CreateAccountWithPassword(ctx context.Context, arg CreateAccountWithPasswordParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccountWithPassword, arg.Email, arg.Username, arg.Password)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Avatar,
		&i.Cover,
		&i.Description,
		&i.Status,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.TokenVersion,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT account_id, email, username, password, avatar, cover, description, status, token_version FROM account
WHERE email = $1
`

type GetAccountByEmailRow struct {
	AccountID    uuid.UUID      `json:"account_id"`
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	Password     sql.NullString `json:"password"`
	Avatar       string         `json:"avatar"`
	Cover        string         `json:"cover"`
	Description  sql.NullString `json:"description"`
	Status       AccountStatus  `json:"status"`
	TokenVersion int32          `json:"token_version"`
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Avatar,
		&i.Cover,
		&i.Description,
		&i.Status,
		&i.TokenVersion,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT account_id, email, username, password, avatar, cover, description, status, token_version FROM account
WHERE username = $1
`

type GetAccountByUsernameRow struct {
	AccountID    uuid.UUID      `json:"account_id"`
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	Password     sql.NullString `json:"password"`
	Avatar       string         `json:"avatar"`
	Cover        string         `json:"cover"`
	Description  sql.NullString `json:"description"`
	Status       AccountStatus  `json:"status"`
	TokenVersion int32          `json:"token_version"`
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Avatar,
		&i.Cover,
		&i.Description,
		&i.Status,
		&i.TokenVersion,
	)
	return i, err
}

const getTokenVersion = `-- name: GetTokenVersion :one
SELECT token_version FROM account
WHERE account_id = $1
`

func (q *Queries) GetTokenVersion(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTokenVersion, accountID)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const incrementTokenVersion = `-- name: IncrementTokenVersion :exec
UPDATE account
SET token_version = token_version + 1
WHERE account_id = $1
`

func (q *Queries) IncrementTokenVersion(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementTokenVersion, accountID)
	return err
}

const isAccountRegistered = `-- name: IsAccountRegistered :one
SELECT EXISTS (
    SELECT 1 FROM account WHERE oauth_provider = $1 AND oauth_provider_id = $2
)
`

type IsAccountRegisteredParams struct {
	OauthProvider   sql.NullString `json:"oauth_provider"`
	OauthProviderID sql.NullString `json:"oauth_provider_id"`
}

func (q *Queries) IsAccountRegistered(ctx context.Context, arg IsAccountRegisteredParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountRegistered, arg.OauthProvider, arg.OauthProviderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loginWithOAuth = `-- name: LoginWithOAuth :one
SELECT account_id, email, username, avatar, cover, description, status, token_version FROM account
WHERE oauth_provider = $1 AND oauth_provider_id = $2
`

type LoginWithOAuthParams struct {
	OauthProvider   sql.NullString `json:"oauth_provider"`
	OauthProviderID sql.NullString `json:"oauth_provider_id"`
}

type LoginWithOAuthRow struct {
	AccountID    uuid.UUID      `json:"account_id"`
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	Avatar       string         `json:"avatar"`
	Cover        string         `json:"cover"`
	Description  sql.NullString `json:"description"`
	Status       AccountStatus  `json:"status"`
	TokenVersion int32          `json:"token_version"`
}

func (q *Queries) LoginWithOAuth(ctx context.Context, arg LoginWithOAuthParams) (LoginWithOAuthRow, error) {
	row := q.db.QueryRowContext(ctx, loginWithOAuth, arg.OauthProvider, arg.OauthProviderID)
	var i LoginWithOAuthRow
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Avatar,
		&i.Cover,
		&i.Description,
		&i.Status,
		&i.TokenVersion,
	)
	return i, err
}
