// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO video (title, description, publisher_id)
VALUES ($1, $2, $3)
RETURNING video_id, title, duration, description, created_at, updated_at, publisher_id, status
`

type CreateVideoParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	PublisherID uuid.UUID      `json:"publisher_id"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo, arg.Title, arg.Description, arg.PublisherID)
	var i Video
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Duration,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublisherID,
		&i.Status,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT 
    v.video_id, v.title, v.duration, v.description, v.created_at, v.status,
    a.account_id, a.username,
    (SELECT COUNT(*) FROM subscribe s WHERE s.subscribe_to_id = v.publisher_id) AS total_subscriber,
    (SELECT COUNT(*) FROM watch_video wv WHERE wv.video_id = v.video_id) AS total_view,
    (SELECT COUNT(*) FROM like_video lv WHERE lv.video_id = v.video_id) AS total_like
FROM video v 
JOIN account a ON a.account_id = v.publisher_id
WHERE v.video_id = $1
`

type GetVideoRow struct {
	VideoID         uuid.UUID      `json:"video_id"`
	Title           string         `json:"title"`
	Duration        int32          `json:"duration"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"created_at"`
	Status          VideoStatus    `json:"status"`
	AccountID       uuid.UUID      `json:"account_id"`
	Username        string         `json:"username"`
	TotalSubscriber int64          `json:"total_subscriber"`
	TotalView       int64          `json:"total_view"`
	TotalLike       int64          `json:"total_like"`
}

func (q *Queries) GetVideo(ctx context.Context, videoID uuid.UUID) (GetVideoRow, error) {
	row := q.db.QueryRowContext(ctx, getVideo, videoID)
	var i GetVideoRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Duration,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
		&i.AccountID,
		&i.Username,
		&i.TotalSubscriber,
		&i.TotalView,
		&i.TotalLike,
	)
	return i, err
}

const publishVideo = `-- name: PublishVideo :one
UPDATE video
SET status = 'published'
WHERE video_id = $1
RETURNING video_id, title, duration, description, created_at, updated_at, publisher_id, status
`

func (q *Queries) PublishVideo(ctx context.Context, videoID uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, publishVideo, videoID)
	var i Video
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Duration,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublisherID,
		&i.Status,
	)
	return i, err
}

const updateVideoDuration = `-- name: UpdateVideoDuration :exec
UPDATE video
SET duration = $2
WHERE video_id = $1
`

type UpdateVideoDurationParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Duration int32     `json:"duration"`
}

func (q *Queries) UpdateVideoDuration(ctx context.Context, arg UpdateVideoDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoDuration, arg.VideoID, arg.Duration)
	return err
}
